repository: flavioespinoza/datedash.doc

release:
  &release 1.0.39

releases:
  - *release
  - 1.0.38
  - 1.0.37
  - 1.0.36
  - 1.0.35

brand_color: "#3492ff"
description: A JavaScript Date utility library boiled down to the essentials. Inspired by Lodash.

css:
  all:
    - /assets/css/main.css

js:
  all:
    - /assets/js/boot.js

  docs:
    - /assets/js/docs.js

  home:
    - /assets/js/home.js

links:
  build_differences:
    https://github.com/flavioespinoza/datedash

  docs_v1:
    https://github.com/flavioespinoza/datedash/doc/README.md

  org:
    https://github.com/flavioespinoza/datedash

  raw:
    https://raw.githubusercontent.com/flavioespinoza/datedash

  repo:
    https://github.com/flavioespinoza/datedash

sass:
  sass_dir:
    assets/css

builds:
  *release:
    href: https://cdn.jsdelivr.net/npm/datedash@1.0.39/datedash.min.js
    integrity: sha384-CABr7+WPGheg2wDpYnF1Bm9XZMqmxEUbWbTEVL9sc8qHmSp7T2seWcVMc+rD5LJD

  1.0.38:  
    href: https://cdn.jsdelivr.net/npm/datedash@1.0.38/datedash.min.js
    integrity: sha384-cPb3x/Es3B6vXhYyDNhqqz7Ire1jgprCcCBp0UCUp0nokGf/zYvjHM5zau8j2Ozd

  1.0.37:  
    href: https://cdn.jsdelivr.net/npm/datedash@1.0.37/datedash.min.js
    integrity: sha384-Gb3VZORAGRy7ooIP34z7Hz2L6TZvP1iCCVHJAeqMcHkcM9bJHujz048/kqLyJUj3

  1.0.36:  
    href: https://cdn.jsdelivr.net/npm/datedash@1.0.36/datedash.min.js
    integrity: sha384-aIzULKkrKq+mN33g77nT6IEyOax/nXBJiCYdClcwkb/tLRup0a7RUC+ycOhTXPQh

  1.0.35:  
    href: https://cdn.jsdelivr.net/npm/datedash@1.0.35/datedash.min.js
    integrity: sha384-bk2uSoeGWRwK0F0UIJG+yNu7kVoa33IiW04wfHZ0m+A8mdb6CWCQP/8IUf7uyDmG

font-face:
  fontawesome:
    regular:
      - https://cdn.jsdelivr.net/fontawesome/4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0
      - https://cdn.jsdelivr.net/fontawesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0

  sourcecodepro:
    light:
      - https://fonts.gstatic.com/s/sourcecodepro/v6/leqv3v-yTsJNC7nFznSMqSP2LEk6lMzYsRqr3dHFImA.woff2
    semi-bold:
      - https://fonts.gstatic.com/s/sourcecodepro/v6/leqv3v-yTsJNC7nFznSMqczFoXZ-Kj537nB_-9jJhlA.woff2

vendor:
  css:
    - href: https://cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css
      integrity: sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN

  js:
    - href: https://embed.runkit.com/
      async: true

    - href: https://cdn.jsdelivr.net/g/fuse@2.6.1,react@15.4.0(react.min.js+react-dom.min.js
      integrity: sha384-txLSiuN1HJSO1or/mE1Y6bvgD0cV3WA6Ss7rs9WqvPQ3zthR8w/DzHpB+DVTDAMz

carbon_ads:
  href: https://cdn.carbonads.com/carbon.js?serve=CKYIEK37&placement=lodashcom
  id: _carbonads_js

google_analytics:
  href: https://www.google-analytics.com/analytics.js
  commands: [['create', 'UA-ACCOUNT-ID', 'auto'], ['require', 'linkid'], ['send', 'pageview']]
  accounts:
    datedash.doc: 'UA-136250397-1'

exclude:
  - node_modules
  - Gemfile
  - gulpfile.js
  - icons.js
  - LICENSE
  - package.json
  - "*.lock"
  - "*.log"
  - "*.md"
  - "*.toml"

include:
  - _headers
  - _redirects
